//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stone.Cobrancas.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stone.Cobrancas.Application.Resources.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cpf informado na busca é inválido..
        /// </summary>
        public static string BUSCA_CPF_INVALIDO {
            get {
                return ResourceManager.GetString("BUSCA_CPF_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para realizar a busca é necessario informar um cpf ou ano/mês de referência..
        /// </summary>
        public static string BUSCA_INVALIDA {
            get {
                return ResourceManager.GetString("BUSCA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ano informado na busca deve ser maior que 1900..
        /// </summary>
        public static string BUSCA_INVALIDA_ANO {
            get {
                return ResourceManager.GetString("BUSCA_INVALIDA_ANO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O mês informado na busca deve estar entre 1 e 12..
        /// </summary>
        public static string BUSCA_INVALIDA_MES {
            get {
                return ResourceManager.GetString("BUSCA_INVALIDA_MES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor informado em página é invalido para a busca..
        /// </summary>
        public static string BUSCA_INVALIDA_PAGINA {
            get {
                return ResourceManager.GetString("BUSCA_INVALIDA_PAGINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor informado em quantidade é invalido para a busca..
        /// </summary>
        public static string BUSCA_INVALIDA_QUANTIDADE {
            get {
                return ResourceManager.GetString("BUSCA_INVALIDA_QUANTIDADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cpf informado na cobrança é inválido..
        /// </summary>
        public static string COBRANCA_CPF_INVALIDO {
            get {
                return ResourceManager.GetString("COBRANCA_CPF_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF da cobrança é obrigatório..
        /// </summary>
        public static string COBRANCA_CPF_OBRIGATORIO {
            get {
                return ResourceManager.GetString("COBRANCA_CPF_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data da cobrança deve ter o ano maior que 1900..
        /// </summary>
        public static string COBRANCA_DATA_INVALIDA {
            get {
                return ResourceManager.GetString("COBRANCA_DATA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data da cobrança é obrigatória..
        /// </summary>
        public static string COBRANCA_DATA_OBRIGATORIO {
            get {
                return ResourceManager.GetString("COBRANCA_DATA_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor da cobrança deve ser maior que 0..
        /// </summary>
        public static string COBRANCA_VALOR_INVALIDO {
            get {
                return ResourceManager.GetString("COBRANCA_VALOR_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor da cobrança é obrigatório..
        /// </summary>
        public static string COBRANCA_VALOR_OBRIGATORIO {
            get {
                return ResourceManager.GetString("COBRANCA_VALOR_OBRIGATORIO", resourceCulture);
            }
        }
    }
}
